export const LOAD_RECORDS = 'accessor/Record/LOAD_RECORDS'
export const LOAD_RECORDS_SUCCESS = 'accessor/Record/LOAD_RECORDS_SUCCESS'
export const LOAD_RECORDS_ERROR = 'accessor/Record/LOAD_RECORDS_ERROR'
export const SET_RECORD_ACTIVE = 'accessor/Record/SET_RECORD_ACTIVE'
export const SET_BRANCH_ACTIVE = 'accessor/Record/SET_BRANCH_ACTIVE'