export const LOAD_RECORDS = 'accessor/Record/LOAD_RECORDS'
export const LOAD_RECORDS_SUCCESS = 'accessor/Record/LOAD_RECORDS_SUCCESS'
export const LOAD_RECORDS_ERROR = 'accessor/Record/LOAD_RECORDS_ERROR'
export const MOVE_RECORD = 'accessor/Record/MOVE_RECORD'
export const SELECT_RECORD = 'accessor/Record/SELECT_RECORD'
export const NAVIGATE_TO_ROOT = 'accessor/Record/NAVIGATE_TO_ROOT'
export const RECORD_HAS_CHANGED = 'accessor/Record/RECORD_HAS_CHANGED'
